on: push
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 21
          distribution: adopt
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Clone dvbinspector repo
        run: git clone --depth 1 https://github.com/EricBerendsen/dvbinspector
      - name: Build dvbinspector
        run: |
          cd dvbinspector
          mvn install
          cd ..
      - name: Build EPG reader
        run: mvn package
      - name: Upload build artifact
        uses: astertom/nexus-upload-artifact@v1
        with:
          pattern: target/ts*.jar
